### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by jacobgantzpolyglot** [CakeTheLiar/launchhelper#2]
Current thread 0x00000ba8 (most recent call first):
<no Python frame>
Attaching...
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'C:\users\nightmares13\AppData\Local\Programs\Python\Python38\p
ython.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\users\\nightmares13\\AppData\\Local\\Programs\\Pyt
hon\\Python38\\python.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.executable = 'C:\\users\\nightmares13\\AppData\\Local\\Programs\\Python\\P
ython38\\python.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\users\\nightmares13\\AppData\\Local\\Programs\\Python\\Python38\\python
38.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\users\\nightmares13\\AppData\\Local\\Programs\\Python\\Python38',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the file
system encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000138 (most recent call first):
<no Python frame>
Found LeagueClientUx.exe: pid 7490
Waiting for port 37805
Attaching...
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'C:\users\nightmares13\AppData\Local\Programs\Python\Python38\p
ython.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\users\\nightmares13\\AppData\\Local\\Programs\\Pyt
hon\\Python38\\python.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.executable = 'C:\\users\\nightmares13\\AppData\\Local\\Programs\\Python\\P
ython38\\python.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\users\\nightmares13\\AppData\\Local\\Programs\\Python\\Python38\\python
38.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\users\\nightmares13\\AppData\\Local\\Programs\\Python\\Python38',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the file
system encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000007cc (most recent call first):
<no Python frame>
Attaching...
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'C:\users\nightmares13\AppData\Local\Programs\Python\Python38\p
ython.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\users\\nightmares13\\AppData\\Local\\Programs\\Pyt
hon\\Python38\\python.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.executable = 'C:\\users\\nightmares13\\AppData\\Local\\Programs\\Python\\P
ython38\\python.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\users\\nightmares13\\AppData\\Local\\Programs\\Python\\Python38\\python
38.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\users\\nightmares13\\AppData\\Local\\Programs\\Python\\Python38',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the file
system encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000007d4 (most recent call first):
<no Python frame>
^CTraceback (most recent call last):
  File "launchhelper2.py", line 214, in <module>
    time.sleep(sleep_time)
KeyboardInterrupt

I tried changing the launcher.sh file

#!/usr/bin/env sh

pkexec sh -c 'sysctl -w abi.vsyscall32=0'

python3 launchhelper2.py

to 
#!/usr/bin/env sh

pkexec sh -c 'sysctl -w abi.vsyscall32=0'

python launchhelper2.py

nightmares13@jacobgantz:~/Desktop$ ./launcher.sh
abi.vsyscall32 = 0
  File "launchhelper2.py", line 70
    filename = f'python-{python_version}-{arch}.exe'
                                                   ^
SyntaxError: invalid syntax

**Comment by jacobgantzpolyglot** [comment]
but those main error messages are from
#!/usr/bin/env sh

pkexec sh -c 'sysctl -w abi.vsyscall32=0'

python3 launchhelper2.py

**Comment by CakeTheLiar** [comment]
I was able to find these related issues: 
https://bugs.python.org/issue27054
https://bugs.python.org/issue39051
https://bugs.python.org/issue42438 

This appears to be a problem with your Python install or venv if you're using one. Reinstalling Python or recreating the venv can apparently fix this.
You can ignore the other mentioned solution in those links to unset `PYTHONHOME` since you already don't have it set.

To me it looks like changing `python3` to `python` will call a Python2 install, which the script is not compatible with. You can verify this by running `python3 --version` and `python --version` respectively.
